### ISSUE TITLE
Decide on final colour scheme for website and logo

### ISSUE THREAD

**Issue by tmheunis** [abcd-j/website#11]
<img width="1407" alt="colour_option_1" src="https://github.com/abcd-j/website/assets/11378509/e2c70e33-ad9b-4a6f-880b-c86561fcf391">
<img width="1408" alt="colour_option_2" src="https://github.com/abcd-j/website/assets/11378509/a7d325e5-dba3-4b32-b2d3-e0ef26cb774d">
<img width="1415" alt="colour_option_3" src="https://github.com/abcd-j/website/assets/11378509/2c322682-c951-49fd-b8be-c3a68e12b699">

**Comment by adswa** [comment]
No clear preference; in a forced-choice voting scenario I'd say 3

**Comment by jsheunis** [comment]
Agree with @adswa
