### ISSUE TITLE
Add visualization(s) of ABCD-J pipeline

### ISSUE THREAD

**Issue by tmheunis** [abcd-j/website#6]
The idea is to add this to the main page:

- JTrack -> DataLad -> JuLearn
- with mHealth -> Data Management -> machine-learning as captions

There could also be another visualization that shows the role of all the participating institutions in the project, similar to the following from a project poster:

<img width="966" alt="Screenshot 2023-12-14 at 09 21 19" src="https://github.com/abcd-j/website/assets/11378509/8bd3f5b8-d59f-46b4-8a90-13eec1c6fb59">

**Comment by jsheunis** [comment]
I created a draft of the first visualization, will add it to https://github.com/abcd-j/website/pull/13
